//sign in
export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
//sign out
export const USER_SIGNOUT = "USER_SIGNOUT";
// send messagee
export const USER_SEND_MESSAGE_REQUEST="USER_SEND_MESSAGE_REQUEST";
export const USER_SEND_MESSAGE_SUCCESS="USER_SEND_MESSAGE_SUCCESS";
export const USER_SEND_MESSAGE_FAIL="USER_SEND_MESSAGE_FAIL";
// request call
export const USER_SEND_CALL_REQUEST="USER_SEND_CALL_REQUEST";
export const USER_SEND_CALL_SUCCESS="USER_SEND_CALL_SUCCESS";
export const USER_SEND_CALL_FAIL="USER_SEND_CALL_FAIL";